version: 2.1 

workflows:
  test-deploy:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout 
      - run:
          name: Install all dependencies
          command: yarn 
      - run: 
          name: Run test
          command: yarn test
      
