version: 2.1 

workflows:
  test-deploy:
    jobs:
      - test
  schedule-deploy:
    triggers:
      - schedule: 
        cron: "0 0 12 * * ?"
        filters:
          branches:
            only:
              - main
    jobs:
      - test
      - deploy
jobs:
  test:
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout 
      - run:
          name: Install all dependencies
          command: yarn 
      - run: 
          name: Run test
          command: yarn test
  deploy: 
    docker:
      - image: cimg/node:14.15.0
    steps: 
      - checkout 
      - run: 
        name: Deploy 
        command: echo "I am deploying"
        
      
